# Generated by Django 3.1.6 on 2021-02-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0002_auto_20210201_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/post_cover/', verbose_name='تصویر'),
        ),
    ]
