# Generated by Django 3.1.6 on 2021-02-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0005_auto_20210202_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='likecomment',
            options={'verbose_name': 'پسندیدن نظر', 'verbose_name_plural': 'پسندیدن نظرات'},
        ),
        migrations.AlterModelOptions(
            name='likepost',
            options={'verbose_name': 'پسندیدن مطلب', 'verbose_name_plural': 'پسندیدن مطالب'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'مطلب', 'verbose_name_plural': 'مطلب ها'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها'},
        ),
        migrations.AddField(
            model_name='category',
            name='sup_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_blog.category', verbose_name='دسته بندی پدر'),
        ),
    ]
