# Generated by Django 3.1.6 on 2021-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0006_auto_20210202_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=350, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان مطلب'),
        ),
    ]
