# Generated by Django 3.1.6 on 2021-02-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0007_auto_20210202_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
