# Generated by Django 3.1.6 on 2021-02-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0008_auto_20210202_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sup_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_blog.category', verbose_name='دسته بندی پدر'),
        ),
    ]
