# Generated by Django 3.1.6 on 2021-02-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0010_auto_20210202_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(upload_to='post_cover/', verbose_name='تصویر کاور'),
        ),
    ]
